export const CLOSE_DOCUMENT = 'CLOSE_DOCUMENT';

export const DOCUMENTS_REQUEST = 'DOCUMENTS_REQUEST';
export const DOCUMENTS_SUCCESS = 'DOCUMENTS_SUCCESS';
export const DOCUMENTS_FAILURE = 'DOCUMENTS_FAILURE';

export const DOCUMENTS_ADD_REQUEST = 'DOCUMENTS_ADD_REQUEST';
export const DOCUMENTS_ADD_SUCCESS = 'DOCUMENTS_ADD_SUCCESS';
export const DOCUMENTS_ADD_FAILURE = 'DOCUMENTS_ADD_FAILURE';

export const DOCUMENTS_GET_REQUEST = 'DOCUMENT_GET_REQUEST';
export const DOCUMENTS_GET_SUCCESS = 'DOCUMENT_GET_SUCCESS';
export const DOCUMENTS_GET_FAILURE = 'DOCUMENT_GET_FAILURE';

export const DOCUMENTS_UPDATE_REQUEST = 'DOCUMENT_UPDATE_REQUEST';
export const DOCUMENTS_UPDATE_SUCCESS = 'DOCUMENT_UPDATE_SUCCESS';
export const DOCUMENTS_UPDATE_FAILURE = 'DOCUMENT_UPDATE_FAILURE';

export const DOCUMENTS_DELETE_REQUEST = 'DOCUMENT_DELETE_REQUEST';
export const DOCUMENTS_DELETE_SUCCESS = 'DOCUMENT_DELETE_SUCCESS';
export const DOCUMENTS_DELETE_FAILURE = 'DOCUMENT_DELETE_FAILURE';

export const SET_DOCUMENTS_SEARCH_FILTER = 'SET_DOCUMENTS_SEARCH_FILTER';

